### ISSUE TITLE
Change in deferred-queue

### ISSUE THREAD

**Issue by gagle** [spion/async-compare#13]
Can you change the example `callbacks-deferred-queue.js`?

[Lines 67-70](https://github.com/spion/async-compare/blob/master/examples/callbacks-deferred-queue.js#L67-70) must be changed by:

``` javascript
.push (function afterFileUpdated(callback) {
  tx.commit(callback);
})
.push (done);
```

**Comment by spion** [comment]
Why didn't you submit a pull request? Done though :)
